<?php

declare(strict_types=1);

namespace MightyPDF\Tests\Support;

use MightyPDF\Assembler\Dictionary;
use MightyPDF\Assembler\PdfObject;
use MightyPDF\Assembler\Stream;
use MightyPDF\Assembler\Types\PdfArray;
use MightyPDF\Assembler\Types\PdfHexString;
use MightyPDF\Assembler\Types\PdfInteger;
use MightyPDF\Assembler\Types\PdfName;
use MightyPDF\Assembler\Types\PdfRectangle;
use MightyPDF\Assembler\Types\PdfReference;
use MightyPDF\Assembler\Types\PdfString;
use MightyPDF\Crypt\CryptTransform;
use MightyPDF\Crypt\Rc4;
use MightyPDF\Crypt\StandardSecurityHandler;

/**
 * Builds encrypted PDFs to test decryption against.
 *
 * MightyPDF has no encryption *writer* -- it only preserves encryption
 * that is already there -- so the /O and /U hashes are computed here, in
 * the tests, rather than borrowed from the code under test. That keeps the
 * check from being circular in the way it would be if the fixture were
 * generated by simply running the reader backwards.
 *
 * The files this produces have been confirmed to open in poppler and
 * Ghostscript, both of which decrypt the strings and streams inside and
 * report no warnings. Two independent implementations agreeing that these
 * are valid is what makes them worth testing against; if this class is
 * ever changed, that is worth re-checking by hand.
 */
final class EncryptedPdfFixture
{
    private const string PAD = "\x28\xBF\x4E\x5E\x4E\x75\x8A\x41\x64\x00\x4E\x56\xFF\xFA\x01\x08"
        . "\x2E\x2E\x00\xB6\xD0\x68\x3E\x80\x2F\x0C\xA9\xFE\x64\x53\x69\x7A";

    private const string FIRST_ID = '****************';
    private const int PERMISSIONS = -4;

    public const string OWNER_PASSWORD = 'owner-secret';

    /** The text drawn on the page of every fixture below. */
    public const string PAGE_TEXT = 'Confidential contents';

    /** The value of /Title in the document information dictionary. */
    public const string TITLE = 'A title that is itself encrypted';

    /** RC4 at 128 bits -- /V 2 /R 3, the most common legacy arrangement. */
    public static function rc4(string $userPassword = ''): string
    {
        $encrypt = (new Dictionary())
            ->set('Filter', new PdfName('Standard'))
            ->set('V', new PdfInteger(2))
            ->set('R', new PdfInteger(3))
            ->set('Length', new PdfInteger(128))
            ->set('P', new PdfInteger(self::PERMISSIONS));

        return self::assemble(self::withLegacyHashes($encrypt, 3, 16, $userPassword), $userPassword);
    }

    /** RC4 at 40 bits -- /V 1 /R 2, the original 1996 scheme. */
    public static function rc4Weak(): string
    {
        $encrypt = (new Dictionary())
            ->set('Filter', new PdfName('Standard'))
            ->set('V', new PdfInteger(1))
            ->set('R', new PdfInteger(2))
            ->set('P', new PdfInteger(self::PERMISSIONS));

        return self::assemble(self::withLegacyHashes($encrypt, 2, 5, ''));
    }

    /**
     * AES-128 -- /V 4 /R 4 with an /AESV2 crypt filter.
     *
     * Deliberately carries no /Length in the /Encrypt dictionary, which is
     * what the spec asks for at /V 4 and what Ghostscript warns about when
     * it is present. The key length has to come from the crypt filter
     * instead.
     */
    public static function aes128(): string
    {
        $encrypt = (new Dictionary())
            ->set('Filter', new PdfName('Standard'))
            ->set('V', new PdfInteger(4))
            ->set('R', new PdfInteger(4))
            ->set('CF', (new Dictionary())->set('StdCF', (new Dictionary())
                ->set('CFM', new PdfName('AESV2'))
                ->set('Length', new PdfInteger(16))
                ->set('AuthEvent', new PdfName('DocOpen'))))
            ->set('StmF', new PdfName('StdCF'))
            ->set('StrF', new PdfName('StdCF'))
            ->set('P', new PdfInteger(self::PERMISSIONS));

        return self::assemble(self::withLegacyHashes($encrypt, 4, 16, ''));
    }

    /** AES-256 -- /V 5 /R 6, the PDF 2.0 scheme. */
    public static function aes256(): string
    {
        $fileKey = str_repeat("\x5A", 32);
        $userSalts = str_repeat("\x11", 8) . str_repeat("\x22", 8);
        $ownerSalts = str_repeat("\x33", 8) . str_repeat("\x44", 8);

        $user = self::hash2b('', substr($userSalts, 0, 8), '') . $userSalts;
        $userKey = self::hash2b('', substr($userSalts, 8, 8), '');

        $owner = self::hash2b(self::OWNER_PASSWORD, substr($ownerSalts, 0, 8), $user) . $ownerSalts;
        $ownerKey = self::hash2b(self::OWNER_PASSWORD, substr($ownerSalts, 8, 8), $user);

        $encrypt = (new Dictionary())
            ->set('Filter', new PdfName('Standard'))
            ->set('V', new PdfInteger(5))
            ->set('R', new PdfInteger(6))
            ->set('CF', (new Dictionary())->set('StdCF', (new Dictionary())
                ->set('CFM', new PdfName('AESV3'))
                ->set('Length', new PdfInteger(32))
                ->set('AuthEvent', new PdfName('DocOpen'))))
            ->set('StmF', new PdfName('StdCF'))
            ->set('StrF', new PdfName('StdCF'))
            ->set('P', new PdfInteger(self::PERMISSIONS))
            ->set('O', PdfString::raw($owner))
            ->set('U', PdfString::raw($user))
            ->set('OE', PdfString::raw(self::wrap($fileKey, $ownerKey)))
            ->set('UE', PdfString::raw(self::wrap($fileKey, $userKey)));

        return self::assemble($encrypt);
    }

    /** Algorithms 3 and 5: the /O and /U hashes for revisions 2 to 4. */
    private static function withLegacyHashes(Dictionary $encrypt, int $revision, int $keyBytes, string $userPassword): Dictionary
    {
        $ownerHash = md5(substr(self::OWNER_PASSWORD . self::PAD, 0, 32), true);

        if ($revision >= 3) {
            for ($i = 0; $i < 50; ++$i) {
                $ownerHash = md5($ownerHash, true);
            }
        }

        $ownerKey = substr($ownerHash, 0, $keyBytes);
        $owner = Rc4::apply($ownerKey, substr($userPassword . self::PAD, 0, 32));

        if ($revision >= 3) {
            for ($i = 1; $i <= 19; ++$i) {
                $owner = Rc4::apply(self::xorWith($ownerKey, $i), $owner);
            }
        }

        $fileKey = md5(
            substr($userPassword . self::PAD, 0, 32)
            . $owner
            . pack('V', self::PERMISSIONS & 0xFFFFFFFF)
            . self::FIRST_ID,
            true,
        );

        if ($revision >= 3) {
            for ($i = 0; $i < 50; ++$i) {
                $fileKey = md5(substr($fileKey, 0, $keyBytes), true);
            }
        }

        $fileKey = substr($fileKey, 0, $keyBytes);

        if ($revision === 2) {
            $user = Rc4::apply($fileKey, self::PAD);
        } else {
            $user = Rc4::apply($fileKey, md5(self::PAD . self::FIRST_ID, true));

            for ($i = 1; $i <= 19; ++$i) {
                $user = Rc4::apply(self::xorWith($fileKey, $i), $user);
            }

            $user = str_pad($user, 32, "\x00");
        }

        return $encrypt->set('O', PdfString::raw($owner))->set('U', PdfString::raw($user));
    }

    /** Algorithm 2.B, the revision 6 password hash. */
    private static function hash2b(string $password, string $salt, string $userData): string
    {
        $k = hash('sha256', $password . $salt . $userData, true);
        $round = 0;

        while (true) {
            $encrypted = openssl_encrypt(
                str_repeat($password . $k . $userData, 64),
                'aes-128-cbc',
                substr($k, 0, 16),
                OPENSSL_RAW_DATA | OPENSSL_ZERO_PADDING,
                substr($k, 16, 16),
            );

            $sum = 0;

            for ($i = 0; $i < 16; ++$i) {
                $sum += ord((string) $encrypted[$i]);
            }

            $k = match ($sum % 3) {
                0 => hash('sha256', (string) $encrypted, true),
                1 => hash('sha384', (string) $encrypted, true),
                default => hash('sha512', (string) $encrypted, true),
            };

            ++$round;

            if ($round >= 64 && ord((string) $encrypted[strlen((string) $encrypted) - 1]) <= $round - 32) {
                return substr($k, 0, 32);
            }
        }
    }

    private static function wrap(string $fileKey, string $intermediateKey): string
    {
        return (string) openssl_encrypt(
            $fileKey,
            'aes-256-cbc',
            $intermediateKey,
            OPENSSL_RAW_DATA | OPENSSL_ZERO_PADDING,
            str_repeat("\x00", 16),
        );
    }

    /** Builds the document and enciphers it with the handler it describes. */
    private static function assemble(Dictionary $encrypt, string $userPassword = ''): string
    {
        $id = new PdfArray(new PdfHexString(self::FIRST_ID), new PdfHexString(self::FIRST_ID));
        $handler = StandardSecurityHandler::open($encrypt, $id, $userPassword);

        /** @var array<int, PdfObject> $objects */
        $objects = [
            1 => (new Dictionary(1))->set('Type', new PdfName('Catalog'))->set('Pages', new PdfReference(2)),
            2 => (new Dictionary(2))->set('Type', new PdfName('Pages'))
                ->set('Count', new PdfInteger(1))->set('Kids', new PdfArray(new PdfReference(3))),
            3 => (new Dictionary(3))->set('Type', new PdfName('Page'))->set('Parent', new PdfReference(2))
                ->set('MediaBox', new PdfRectangle(0, 0, 612, 792))
                ->set('Contents', new PdfReference(4))
                ->set('Resources', (new Dictionary())->set('Font',
                    (new Dictionary())->set('F1', new PdfReference(5)))),
            4 => new Stream(4, sprintf("BT /F1 22 Tf 1 0 0 1 60 700 Tm (%s) Tj ET\n", self::PAGE_TEXT), false),
            5 => (new Dictionary(5))->set('Type', new PdfName('Font'))
                ->set('Subtype', new PdfName('Type1'))->set('BaseFont', new PdfName('Helvetica')),
            6 => (new Dictionary(6))->set('Title', PdfString::text(self::TITLE)),
        ];

        $out = "%PDF-1.7\n";
        $offsets = [];

        foreach ($objects as $objectId => $object) {
            $offsets[$objectId] = strlen($out);

            $out .= CryptTransform::apply(
                $object,
                static fn (string $bytes): string => $handler->encryptString($bytes, $objectId, 0),
                static fn (string $bytes): string => $handler->encryptStream($bytes, $objectId, 0),
            )->render(true);
        }

        // The /Encrypt dictionary is the one object left in the clear.
        $encryptObject = new Dictionary(7);

        foreach ($encrypt->entries() as $key => $value) {
            $encryptObject->set((string) $key, $value);
        }

        $offsets[7] = strlen($out);
        $out .= $encryptObject->render(true);

        $xrefOffset = strlen($out);
        $out .= "xref\n0 8\n0000000000 65535 f \n";

        for ($objectId = 1; $objectId <= 7; ++$objectId) {
            $out .= sprintf("%010d 00000 n \n", $offsets[$objectId]);
        }

        return $out
            . "trailer\n<< /Size 8 /Root 1 0 R /Info 6 0 R /Encrypt 7 0 R /ID "
            . $id->format() . " >>\nstartxref\n{$xrefOffset}\n%%EOF\n";
    }

    private static function xorWith(string $key, int $value): string
    {
        $out = '';

        for ($i = 0, $length = strlen($key); $i < $length; ++$i) {
            $out .= chr(ord($key[$i]) ^ $value);
        }

        return $out;
    }
}
