<?php

declare(strict_types=1);

namespace MightyPDF\Tests\Assembler;

use MightyPDF\Assembler\Document;
use PHPUnit\Framework\TestCase;

/**
 * Full round-trip: a Document with one or more blank pages must produce
 * a *structurally valid* PDF. Since no third-party PDF library is
 * available (by design -- see project conventions) or installed, validity
 * is checked with pure string/regex assertions on the output bytes,
 * rather than parsing it with a real reader.
 */
final class DocumentTest extends TestCase
{
    public function testStartsWithVersionHeaderAndEndsWithEof(): void
    {
        $document = new Document();
        $document->newPage();

        $output = $document->save();

        self::assertStringStartsWith("%PDF-1.7\n", $output);
        self::assertStringEndsWith('%%EOF', $output);
    }

    public function testObjEndobjCountsAreBalanced(): void
    {
        $document = new Document();
        $document->newPage();
        $document->newPage();

        $output = $document->save();

        $objCount = preg_match_all('/\d+ 0 obj/', $output);
        $endobjCount = preg_match_all('/endobj/', $output);

        self::assertGreaterThan(0, $objCount);
        self::assertSame($objCount, $endobjCount);
    }

    public function testXrefOffsetsPointExactlyAtEachObjectsOwnMarker(): void
    {
        $document = new Document();
        $document->newPage();
        $document->newPage();
        $document->newPage();

        $output = $document->save();

        preg_match_all('/^(\d{10}) \d{5} n \n/m', $output, $matches);
        self::assertNotEmpty($matches[1], 'Expected at least one "n" xref entry');

        foreach ($matches[1] as $offsetString) {
            $offset = (int) $offsetString;
            self::assertMatchesRegularExpression(
                '/^\d+ 0 obj/',
                substr($output, $offset, 20),
                "Xref offset $offset does not point at an \"N 0 obj\" marker",
            );
        }
    }

    public function testSizeEqualsFreeListHeadPlusRealObjectCount(): void
    {
        // Direct regression coverage for the confirmed 2012 bug: the
        // checked-in legacy test.pdf had a 4-entry xref table ("0 4")
        // but a trailer claiming "/Size 3".
        $document = new Document();
        $document->newPage();
        $document->newPage();

        $output = $document->save();

        $nEntryCount = preg_match_all('/^\d{10} \d{5} n \n/m', $output);
        preg_match('/\/Size (\d+)/', $output, $sizeMatch);

        self::assertSame($nEntryCount + 1, (int) $sizeMatch[1]);
    }

    public function testStartxrefPointsAtTheLiteralXrefKeyword(): void
    {
        $document = new Document();
        $document->newPage();

        $output = $document->save();

        preg_match('/startxref\n(\d+)\n/', $output, $matches);
        self::assertNotEmpty($matches);

        $offset = (int) $matches[1];
        self::assertSame('xref', substr($output, $offset, 4));
    }

    public function testRootReferenceInTrailerPointsAtAnActualCatalogObject(): void
    {
        $document = new Document();
        $document->newPage();

        $output = $document->save();

        preg_match('/\/Root (\d+) 0 R/', $output, $matches);
        self::assertNotEmpty($matches);

        $catalogId = (int) $matches[1];
        self::assertStringContainsString("$catalogId 0 obj\n<< /Type /Catalog", $output);
    }

    public function testEachPageReferencesTheSamePageTreeAsParent(): void
    {
        $document = new Document();
        $document->newPage();
        $document->newPage();

        $output = $document->save();

        preg_match_all('/\/Parent (\d+) 0 R/', $output, $matches);
        self::assertCount(2, $matches[1]);
        self::assertSame($matches[1][0], $matches[1][1]);
    }

    public function testPageTreeCountMatchesNumberOfPagesAdded(): void
    {
        $document = new Document();
        $document->newPage();
        $document->newPage();
        $document->newPage();

        $output = $document->save();

        self::assertStringContainsString('/Type /Pages', $output);
        self::assertStringContainsString('/Count 3', $output);
    }

    public function testXrefSubsectionFieldWidthsMatchRealWriterConventions(): void
    {
        // Structural-shape reference: blank.pdf (a real macOS TextEdit /
        // Quartz PDF, not generated by this library) uses the same
        // 10-digit-offset / 5-digit-generation xref line format.
        $document = new Document();
        $document->newPage();

        $output = $document->save();

        self::assertMatchesRegularExpression('/^0000000000 65535 f $/m', $output);
        self::assertMatchesRegularExpression('/^\d{10} \d{5} n $/m', $output);
    }

    public function testSavingWithNoPagesStillProducesAStructurallyValidDocument(): void
    {
        $document = new Document();

        $output = $document->save();

        self::assertStringStartsWith("%PDF-1.7\n", $output);
        self::assertStringEndsWith('%%EOF', $output);
        self::assertStringContainsString('/Type /Catalog', $output);
    }

    public function testInfoIsWiredIntoTheTrailerAndReferencesARealInfoObject(): void
    {
        $document = new Document();
        $document->newPage();
        $document->info()->setTitle('Quarterly Report');

        $output = $document->save();

        preg_match('/\/Info (\d+) 0 R/', $output, $matches);
        self::assertNotEmpty($matches);

        $infoId = (int) $matches[1];
        self::assertStringContainsString("$infoId 0 obj\n<< /Title (Quarterly Report)", $output);
    }

    public function testSavingWithoutTouchingInfoEmitsNoInfoKeyAtAll(): void
    {
        $document = new Document();
        $document->newPage();

        $output = $document->save();

        self::assertStringNotContainsString('/Info ', $output);
    }

    public function testSaveToFileWritesTheSameBytesAsSave(): void
    {
        $document = new Document();
        $document->newPage();

        $path = tempnam(sys_get_temp_dir(), 'mightypdf-test-');
        self::assertIsString($path);

        try {
            $document->saveToFile($path);
            self::assertSame($document->save(), file_get_contents($path));
        } finally {
            unlink($path);
        }
    }
}
